[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[prune]
  go-tests = true
  unused-packages = true
